todo1project/todo1app/urls.py
from . import views
from django.urls import path
app_name = 'todo1app'


urlpatterns=[
    path('',views.add,name='add'),
    path('delete/<int:task_id>/', views.delete, name='delete'),
    path('upadte/<int:id>/', views.update, name='update'),
    path('cbvhome/',views.Tasklistview.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.Taskdetailview.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.Taskupdateview.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/',views.Taskdeleteview.as_view(),name='cbvdelete'),
]

todo1project/todo1project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("todo1app.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todo1project/todo1app/models.py
from django.db import models


class Task(models.Model):
    name = models.CharField(max_length=250)
    priority = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return self.name

todo1project/todo1app/forms.py
from .models import Task
from django import forms


class TodoForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'priority', 'date']

todo1project/todo1app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .models import Task
from .forms import TodoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView


class Taskdeleteview(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todo1app:cbvhome')


class Taskupdateview(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name', 'priority', 'date')

    def get_success_url(self):
        return reverse_lazy('todo1app:cbvdetail', kwargs={'pk': self.object.id})


class Taskdetailview(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'


class Tasklistview(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task1'


# Create your views here.
def add(request):
    task1 = Task.objects.all()
    if request.method == 'POST':
        name = request.POST.get('task', '')
        priority = request.POST.get('priority', '')
        date = request.POST.get('date', '')
        task = Task(name=name, priority=priority, date=date)
        task.save()
    return render(request, 'home.html', {'task1': task1})


# def details(request):
#
#     return render(request,'details.html')

def delete(request, task_id):
    task = Task.objects.get(id=task_id)
    if request.method == 'POST':
        task.delete()
        return redirect('/')
    # return render(request, 'delete.html')


def update(request, id):
    task = Task.objects.get(id=id)
    f = TodoForm(request.POST or None, instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request, 'edit.html', {'f': f, 'task': task})

todo1project/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script>
        function myFunction() {
            const r = confirm("Are You Sure You Want to Delete!");
            return r === true;
        }
    </script>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todo1project/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
        {% csrf_token %}
    <p>Are you sure if this task is done?</p>
    <button type="submit">Confirm</button>
</form>
{% endblock %}

todo1project/templates/detail.html
  {% extends 'base.html' %}
  {% block content %}
    <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{task.name}}</h5>
                    <p><b>{{task.priority}}</b></p>
                    <p><b>{{task.date}}</b></p>
{#                    <a class="btn btn-danger" href="{% url 'todo1app:delete' i.id %}">Done</a>#}
                    <form method="post" action="{% url 'todo1app:cbvdelete' task.id %}">
                         {% csrf_token %}
                        <button class="btn btn-danger" >Done</button>
                    </form><br>
                    <a class="btn btn-success" href="{% url 'todo1app:cbvupdate' task.id %}">Update</a>
                </div>
            </div>
  {% endblock %}

todo1project/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
        {% csrf_token %}
    {{f.as_p}}
    <button type="submit">Confirm</button>
</form>
{% endblock %}

todo1project/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
        <form method="POST" class="p-3 shadow">
             {% csrf_token %}
            <div class="form-group">
                <label for="task"></label>
                    <input type="text" class="form-control" id="task" name="task" placeholder="Taskname">
            </div>
            <div class="form-group">
                <label for="priority"></label>
                    <input type="text" class="form-control" id="priority" name="priority" placeholder="Enter your Priority">
            </div>
            <div class="form-group">
                <label for="date"></label>
                    <input type="date" class="form-control" id="date" name="date" placeholder="Enter the date">
            </div>

       <div style="text-align: center;margin-top: 10px;">
      <input  type="submit" class="btn btn-success">
       </div>
        </form>
        </div>
        <div class="col-md-6">
            <h4>Task to be Completed</h4>
            {% for i in task1 %}
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>
{#                    <a class="btn btn-danger" href="{% url 'todo1app:delete' i.id %}">Done</a>#}
                    <form method="post" action="{% url 'todo1app:delete' i.id %}" onsubmit="return myFunction(this)">
                         {% csrf_token %}
                        <button class="btn btn-danger" >Done</button>
                    </form><br>
                    <a class="btn btn-success" href="{% url 'todo1app:update' i.id %}">Update</a>
                </div>
            </div><br>
            {% endfor %}
        </div>
    </div>
</div>



{% endblock %}

todo1project/templates/update.html
{% extends 'base.html' %}
{% block content %}
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                <h3>Task Update</h3>
            </div>
            <div class="card-body">
                <form method="POST">
                {% csrf_token %}
                    {{form.as_p}}
            <button type="submit">Confirm</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}